0|Catppuccin-Mocha|~/.config/swww/Catppuccin-Mocha/rain_world2.png
0|Catppuccin-Latte|~/.config/swww/Catppuccin-Latte/samurai_bebop.png
0|Decay-Green|~/.config/swww/Decay-Green/moments_before_desk.png
0|Rose-Pine|~/.config/swww/Rose-Pine/mountain_dragon_pink.jpg
0|Tokyo-Night|~/.config/swww/Tokyo-Night/cat_lofi_cafe.jpg
0|Material-Sakura|~/.config/swww/Material-Sakura/material_pastel_4.jpg
0|Graphite-Mono|~/.config/swww/Graphite-Mono/samurai_bebop.png
0|Cyberpunk-Edge|~/.config/swww/Cyberpunk-Edge/david.jpg
0|Frosted-Glass|~/.config/swww/Frosted-Glass/teal_mountain.png
0|Gruvbox-Retro|~/.config/swww/Gruvbox-Retro/minimal_squares.png
1|Pitch-Black|~/.config/swww/Pitch-Black/648115.png
